---
services:
  EMA_rsi30:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/ema.log
      --db-url sqlite:////freqtrade/user_data/dbs/ema.sqlite
      --config /freqtrade/user_data/con_ema.json
      --strategy EMA_rsi30
  BbandRsi:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: BbandRsi
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8081:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/rsi.log
      --db-url sqlite:////freqtrade/user_data/dbs/rsi.sqlite
      --config /freqtrade/user_data/con_rsi.json
      --strategy BbandRsi
  E0V1E_45:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: E0V1E_45
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8082:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/E0V1E_45.log
      --db-url sqlite:////freqtrade/user_data/dbs/E0V1E_45.sqlite
      --config /freqtrade/user_data/E0V1E_45.json
      --strategy E0V1E_45
    
